---
- name: Install Certbot.
  pip: name="{{ certbot_package }}" state=present executable="{{ certbot_install }}"

- name: Set Certbot script variable.
  set_fact:
    certbot_script: /usr/local/bin/certbot
